### ISSUE TITLE
初窥CORB - C的博客 |UlyC

### ISSUE THREAD

**Issue by UlyC** [UlyC/UlyC.github.io#1]
https://ulyc.github.io/2019/08/01/%E5%88%9D%E7%AA%A5CORB/ 

 我见到过地狱与天堂的婚礼，战舰在猎户座肩旁熊熊燃烧！

**Comment by woaixiangbao** [comment]
很多图片都显示不出来了，能补一下吗

**Comment by UlyC** [comment]
> 很多图片都显示不出来了，能补一下吗

我这里看到是全的诶， 你可以发下哪几张吗，可能是要挂梯子， 我看换下图床行不行

**Comment by stanley0614** [comment]
我翻墙过来看，很多图片确实显示不出来 ，能不能把图放在github 仓库

**Comment by luoqishuai** [comment]
大佬,python设计模式该看那些书,或者知识点啊

**Comment by UlyC** [comment]
> 大佬,python设计模式该看那些书,或者知识点啊

大佬不敢当，， 设计模式不一定用哪个语言，主要是思想， 网上挺多python实现各种设计模式的例子，自己随便找些模仿着敲一下代码才是最有用的

**Comment by TLGits** [comment]
附录里面的图片在哪里呀？

**Comment by UlyC** [comment]
> @TLGits
> 附录里面的图片在哪里呀？

哪一篇文章的附录？
